- word counter/README.md
- word counter/index.html
> added word counter

- NotesKeeperApp/KeeperApp-main/README.md
- NotesKeeperApp/KeeperApp-main/package-lock.json
- NotesKeeperApp/KeeperApp-main/package.json
- NotesKeeperApp/KeeperApp-main/public/index.html
- NotesKeeperApp/KeeperApp-main/public/styles.css
- NotesKeeperApp/KeeperApp-main/src/components/App.jsx
- NotesKeeperApp/KeeperApp-main/src/components/CreateArea.jsx
- NotesKeeperApp/KeeperApp-main/src/components/Footer.jsx
- NotesKeeperApp/KeeperApp-main/src/components/Header.jsx
- NotesKeeperApp/KeeperApp-main/src/components/Note.jsx
- NotesKeeperApp/KeeperApp-main/src/index.js
A basic notes app built using ReactJs #50
> Added new project: Notes Keeper App

- Dice Game/dicee.html
- Dice Game/index.js
- Dice Game/styles.css
- word counter/index.html
added a play button so you don't have to click refreh every time
> Added a Play button in dice game 

- Drink Water Reminder/index.html
- Drink Water Reminder/script.js
- Drink Water Reminder/style.css
please review it and merge it under hacktoberfest
> added a drink water reminder using html-css-js

- Movie Seat Booking/index.html
- Movie Seat Booking/script.js
- Movie Seat Booking/style.css
please review it and merge it under hacktoberfest
> added movie seat booking web-app

- EMI Calculator/EMI_Calculator.html
I have added the EMI Calculator which is regarding the issue # 147.
> Hacktoberfest2

- Draw Happy Diwali/Happy_Diwali.py
- Draw Happy Diwali/README.md
We will Draw Happy Diwali in Python Turtle. Turtle is a pre-installed Python module that allows users to draw drawings and shapes on a virtual canvas. The onscreen pen used for doodling is known as the turtle. In summary, the Python turtle library provides novice programmers with a fun and interactive approach to learning about Python programming.
> Draw Happy Diwali in Python Turtle  in Python

- Insect Catching Game/index.html
- Insect Catching Game/script.js
- Insect Catching Game/style.css
Can you review it and label it under Hacktober Fest?
> added an insect catching game

- Coin Flipper/index.html
Added a Fun Coin Flipping Game created using HTML language.
> Added a Coin Flipper Project

- 2048/game.js
- 2048/index.html
2048 game implemented using **JavaScript** & **HTML5 cavas**
> Adding my version of 2048 game in JS

- menjaa/index.html
- menjaa/script.js
- menjaa/style.css
- tower-blocks/LICENSE.txt
- tower-blocks/index.html
- tower-blocks/script.js
- tower-blocks/style.css
issue#171  please merge it and name it hacktoberfest @theDeviser
> Added game Menja

- color blast/README.md
- color blast/index.html
- color blast/script.js
- color blast/style.css
- menjaa/README.md
- menjaa/index.html
- menjaa/script.js
- menjaa/style.css
- tower-blocks/LICENSE.txt
- tower-blocks/README.md
- tower-blocks/index.html
- tower-blocks/script.js
- tower-blocks/style.css
#172 completed please merge and assign it as hacktoberfest @theDeviser
> added game color blast

- menjaa/index.html
- menjaa/script.js
- menjaa/style.css
- tower-blocks/LICENSE.txt
- tower-blocks/README.md
- tower-blocks/index.html
- tower-blocks/script.js
- tower-blocks/style.css
#173  added game tower block please merge it and assign it hacktoberfest @theDeviser
> Added tower block

- Encrypt decrypt/main.py
- Encrypt decrypt/readme.md
I created a GUI application to encrypt and decrypt using Python.
> Created encryption and decryption using python

- Maurer/README.md
- Maurer/maurer.py
- Pascal-Tic-Tac-Toe/Readme.md
- Pascal-Tic-Tac-Toe/tictactoe.pas
- Pascal-Tic-Tac-Toe/tictactoe_freepascal.pas
- Maurer Algorithm
- Pascal Tic Tac Toe
> new entries

- Emoji rating app/index.html
- Emoji rating app/index.js
- Emoji rating app/style.css
Added a emoji rating app using HTML-CSS-JS
> Added a emoji rating app

- Mouse-Event/index.html
- Mouse-Event/index.js
- Mouse-Event/style.css
Added a Mouse-Event game using HTML-CSS-JS
> Added a Mouse-Event game

- Bomber Man game/README.md
- Bomber Man game/index.html
- Bomber Man game/script.js
- Bomber Man game/style.css
Added a bomber man game using HTML-CSS-JS
> Added a bomber man game for issue #201

- The Organizer/THE_ORGANIZER.py
_Full_ info : `https://github.com/mishrabiswajit/THE-ORGANIZER/releases/tag/v3.2.0`
> The Organizer

- Passsword Generator/password_generator.py
About : This is a small python program which has a exe version for windows to generate most secure password
> Password Generator :-
